{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.slprime",
    "module": "ChromaticTooltips",
    "version": "1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ChromaticTooltips-1.0.9-dev.jar",
          "url": "ChromaticTooltips-1.0.9-dev.jar",
          "size": 220562,
          "sha512": "fa3f39cdb7fb837295e201df5b1f6ed68877b04267f17e165e4b58e9a01fc6d4609bacb1975312097b9a9636b2d74f16e0be8d9ead1761212da8a1630cdf3d94",
          "sha256": "4e7b2786aeeacdd55dbbd29d5f234f52b6641ff64c4ffd6307768bc8085c5b0f",
          "sha1": "b636e0c54d4e2d5b5d63eb322bba0ed011249700",
          "md5": "fb4fe8158bdd12f4cf88106127d50158"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.legacymoddingmc",
          "module": "unimixins",
          "version": {
            "requires": "0.1.23"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "unimixins",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.9.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "GTNHLib",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.8.41"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "ChromaticTooltips-1.0.9-dev.jar",
          "url": "ChromaticTooltips-1.0.9-dev.jar",
          "size": 220562,
          "sha512": "fa3f39cdb7fb837295e201df5b1f6ed68877b04267f17e165e4b58e9a01fc6d4609bacb1975312097b9a9636b2d74f16e0be8d9ead1761212da8a1630cdf3d94",
          "sha256": "4e7b2786aeeacdd55dbbd29d5f234f52b6641ff64c4ffd6307768bc8085c5b0f",
          "sha1": "b636e0c54d4e2d5b5d63eb322bba0ed011249700",
          "md5": "fb4fe8158bdd12f4cf88106127d50158"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ChromaticTooltips-1.0.9.jar",
          "url": "ChromaticTooltips-1.0.9.jar",
          "size": 222308,
          "sha512": "b6885c20debc9d945e47aa5fcf6a740a08b9f4c8110becb1222f80290f8fbe82fa0b4ac06b3c14fb7db5c934d74ed9fe4df6dbab4c9b16d1834811cfb160407b",
          "sha256": "053d6eef99a54ba7e480d437ecf0de31a21c323da39fe4b4758e610af480f578",
          "sha1": "77e2d363570c07e5b5f12514362b7c7bfe989ba1",
          "md5": "3ec54c0a4bc3ae5f38df25fdefa3a6d3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ChromaticTooltips-1.0.9-sources.jar",
          "url": "ChromaticTooltips-1.0.9-sources.jar",
          "size": 122258,
          "sha512": "563233e23c5da0496cedf3fb5dbe9d9abf346350edf024944ecbee6de6ebe1951168e32c0cc85af8edf3ea699b11ac0fab08a8f6bce312e52f2a27c4cc6a155d",
          "sha256": "5993e1b3786a9f0d5c9aa11c6d69411ac57f4f38f99dc6b23015a396030628dc",
          "sha1": "4d2e58e02f1dc6a2416ca3740a293c7ada711c26",
          "md5": "c0003e64d29f41f655172e4bf0da8b7d"
        }
      ]
    }
  ]
}
